# -*- coding: utf-8 -*-
"""desafio-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ND3elkNUtyYcv7JNVnOdXGC0yIIxMPAn
"""

# Desafio 3:
playlist = {

  "nome": "Galeria Emoji",

  "imagens": [

    {"img1": [(255,255,0), (0,0,0), (255,255,0)]},

    {"img2": [(255,255,0), (255,255,0), (0,0,0)]}

  ]

}



# 1º nível → lista de imagens

for imagem in playlist["imagens"]:



  # 2º nível → dicionário da imagem

  for nome in imagem.keys():



    pixels = imagem[nome]

    novos_pixels = []



    # 3º nível → pixels

    for pixel in pixels:



      # aplica sombra

      if pixel == (255,255,0):

        novo_pixel = (pixel[0]//2, pixel[1]//2, pixel[2]//2)

      else:

        novo_pixel = pixel



      novos_pixels.append(novo_pixel)



    # usa .pop() para remover último pixel

    novos_pixels.pop()



    # usa .insert() para adicionar novo pixel no início

    novos_pixels.insert(0, (0,0,255)) # azul



    # atualiza a imagem

    imagem[nome] = novos_pixels



print("Playlist: ")

for imagem in playlist["imagens"]:

  for nome, pixels in imagem.items():

    print(f"{nome}: {pixels}")



plt.imshow(playlist["imagens"][0]["img1"])

plt.show()