# -*- coding: utf-8 -*-
"""projeto-traduzindo-logica-para-python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16iafIZJq1q8eUTV8EUwAyoeaf05Zg7vb

# **Função: Processar vendas**
"""

# Esta função calcula o total de uma compra, aplicando descontos progressivos e validando o estoque.

def processar_vendas():

    total_compra = 0.0
    itens_comprados = 0

    print("Quantos produtos diferentes foram comprados?")
    quantidade_tipos = int(input("Quantidade de tipos: "))

    for i in range(quantidade_tipos):
        print("Nome do produto: ")
        nome = input("O nome é: ")
        print("Preço unitário: ")
        preco = float(input("O preço é: "))
        print("Quantidade deste produto:")
        qtd = int(input("A quantidade é: "))

        if preco <= 0 or qtd <= 0:
            print(f"Erro: Valores inválidos para {nome}. Este item não será adicionado ao total.")
        else:
            subtotal = preco * qtd
            total_compra += subtotal
            itens_comprados += qtd

    if total_compra > 500.00:
        total_final = total_compra * 0.90
        print("Desconto de 10% aplicado!")
    elif total_compra > 200.00:
        total_final = total_compra * 0.95
        print("Desconto de 5% aplicado!")
    else:
        total_final = total_compra

    print(f"Resumo: {itens_comprados} itens. Total a pagar: R$ {total_final:.2f}")

processar_vendas()

"""# **Função: Analisar clima**"""

# Esta função coleta dados de temperatura de uma semana e gera um relatório de alertas.

def analisar_clima():

    soma_temperaturas = 0.0

    dias_quentes = 0

    alerta_extremo = False



    for dia in range(1, 8):

        temp = float(input(f"Digite a temperatura do dia {dia}: "))

        soma_temperaturas += temp



        if temp > 35.0:

            dias_quentes += 1



        if temp > 45.0 or temp < -5.0:

            alerta_extremo = True

    # Média e relatório final devem ser calculados e impressos após o loop
    media = soma_temperaturas / 7

    print(f"Média semanal: {media:.2f}")

    print(f"Dias acima de 35°C: {dias_quentes}")

    if alerta_extremo:

        print("CUIDADO: Condições climáticas perigosas detectadas!")

    else:

        print("Clima dentro da normalidade operacional.")

analisar_clima()

"""# **Função: Sistema Notas Turma**"""

# Gerencia a entrada de notas de alunos e decide quem precisa de recuperação.

def sistema_notas_turma():

 total_alunos = int(input("Quantos alunos existem na turma? "))



 for j in range(1, total_alunos + 1):

  aluno_nome = input(f"Nome do aluno: ")

  n1 = float(input("Nota 1: "))

  n2 = float(input("Nota 2: "))



  media_aluno = (n1 + n2) / 2



  if media_aluno >= 7.0:

      print(f"{aluno_nome}: Aprovado com média {media_aluno:.2f}")

  elif media_aluno >= 5.0:

      print(f"{aluno_nome}: Recuperação (Média: {media_aluno:.2f})")

  else:

      print(f"{aluno_nome}: Reprovado")

sistema_notas_turma()

"""# **Função: Simulador Poupanca**"""

# Simula o crescimento de um investimento mês a mês com base em aportes variáveis.

def simulador_poupanca():

 saldo = float(input("Valor inicial do investimento: "))

 taxa = float(input("Taxa de juros mensal (em %) "))

 meses = int(input("Número de meses da simulação: "))



 for m in range(1, meses + 1):

    aporte = float(input(f"Quanto deseja depositar no mês {m}? (0 para nenhum): "))



    saldo += aporte

    juros = saldo * (taxa / 100)

    saldo += juros



    print(f"Mês {m}: Saldo atualizado = R$ {saldo:.2f}")



    if saldo > 10000.0:

      print(f"Parabéns! Você atingiu a meta de 10k no mês {m}")



 print(f"Resultado final após {meses} meses: R$ {saldo:.2f}")

simulador_poupanca()

"""# **Questões de Reflexão**
## Sobre Tipagem:
O sistema vai ler como texto (String) e por isso não vai ler como número para que possa realizar as operações.

## Sobre Estruturas:
Para que o laço conte de 1 até o número exato de meses (incluindo o último), a sintaxe deve ser:
range(1, meses + 1)

Por que o Python se comporta assim?
Diferente do pseudocódigo original (onde o limite final é inclusivo), o Python utiliza o modelo de intervalo meio-aberto. No range(início, fim), o valor de início é incluído, mas o valor de fim é exclusivo (parada antes de atingi-lo).
"""