# -*- coding: utf-8 -*-
"""desafio-02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ND3elkNUtyYcv7JNVnOdXGC0yIIxMPAn
"""

# Desafio 2:
biblioteca_musical = {

  "Toques": [

    {"Alegre": ([440, 480], [520, 560])},

    {"Triste": ([200, 150], [100, 50])}

  ]

}



# 1º nível → lista de toques

for toque in biblioteca_musical["Toques"]:



  # 2º nível → dicionário (nome da música)

  for nome, matriz in toque.items():



    # matriz original

    linha1, linha2 = matriz



    nova_matriz = []



    # 3º nível → índices (colunas viram linhas)

    for i in range(len(linha1)):

      nova_linha = []



      nova_linha.append(linha1[i])

      nova_linha.append(linha2[i])



      nova_matriz.append(nova_linha)



    # converter para tupla (igual ao original)

    nova_matriz = (nova_matriz[0], nova_matriz[1])



    # atualiza o dicionário

    toque.update({nome: nova_matriz})



print("Toques: ")

for toque in biblioteca_musical["Toques"]:

  for nome, matriz in toque.items():

    print(f"{nome}: {matriz}")