# -*- coding: utf-8 -*-
"""desafio-01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ND3elkNUtyYcv7JNVnOdXGC0yIIxMPAn
"""

# Desafio 1:
emoji_data = {

  "nome": "Smile",

  "grade": [

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (255,255,0), (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)],

    [(255,255,0), (0,0,0),  (0,0,0),  (0,0,0),  (255,255,0)],

    [(255,255,0), (255,255,0), (255,255,0), (255,255,0), (255,255,0)]

  ]

}



nova_grade = []



# 1º nível → dicionário

for chave, valor in emoji_data.items():



  if chave == "grade":



    # 2º nível → linhas

    for linha in valor:

      nova_linha = []



      # 3º nível → pixels

      for pixel in linha:



        if pixel == (255, 255, 0):

          novo_pixel = (pixel[0]//2, pixel[1]//2, pixel[2]//2)

        else:

          novo_pixel = pixel



        nova_linha.append(novo_pixel)



      nova_grade.append(nova_linha)



# Atualiza o dicionário

emoji_data["grade"] = nova_grade



print(f"Emoji: {emoji_data['nome']}")

for linha in emoji_data["grade"]:

  print(linha)



plt.imshow(emoji_data["grade"])

plt.show()