# -*- coding: utf-8 -*-
"""projeto-algoritimo-de-alditoria-de-dados

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12PViA3TuZfRYJF9FZoMfURFmWbxYcSj4

# Parte 1

## 1.

R: Ela pode “mentir” por conta de que ela pode trazer a magnitude de todo o conjunto não demonstrando a realidade.



## 2.

R: Para que possamos tomar decisões críticas com base na realidade.



## 3.

R: É um valor monetário máximo que o auditor define como aceitável.
"""

# Parte 2

# Configuração Global
LIMITE_SEGURANCA = 10000.0 # Valor máximo sem suspeita permitida

# Função de análise
def analisar_vendas(v1, v2, v3):
    global LIMITE_SEGURANCA # Permite alterar a variável global

    # Cálculo da média
    media = (v1 + v2 + v3) / 3

    print("=~"*40)
    print("=== RESULTADOS ===")
    print(f"Média das vendas: R$ {media:.2f}")
    print("=~"*40)

    # Verifica se a média ultrapassa o limite de segurança
    if media > LIMITE_SEGURANCA:
        print("!"*40)
        print("SISTEMA EM QUARENTENA")
        print("!"*40)

    # Verifica se a venda ultrapassa o limite
    if v1 > LIMITE_SEGURANCA or v2 > LIMITE_SEGURANCA or v3 > LIMITE_SEGURANCA:

        # Simula decisão do gerente
        resposta = input("Essa venda alta é legítima? (s/n): ")


        if resposta.lower() == 's':
            novo_limite = float(input("Digite o novo limite de segurança: "))
            LIMITE_SEGURANCA = novo_limite
            print(f"Novo LIMITE_SEGURANCA definido: {LIMITE_SEGURANCA}")

    # Verifica discrepância (5x maior que a média)
    if v1 > media * 5 or v2 > media * 5 or v3 > media * 5: # Condição impossivel de chegar. Pelos meus testes funcionou trocando o valor de 5 para 2
        print("=~"*40)
        print("MÉDIA ACIMA DO LIMITE!!! REVISÃO MANUAL NECESSÁRIA")
        print("=~"*40)


    # Exibir tipos das variáveis
    print("\n--- TIPOS DE DADOS ---")
    print(f"v1: {v1} -> {type(v1)}")
    print(f"v2: {v2} -> {type(v2)}")
    print(f"v3: {v3} -> {type(v3)}")
    print(f"media: {media} -> {type(media)}")
    print(f"LIMITE_SEGURANCA: {LIMITE_SEGURANCA} -> {type(LIMITE_SEGURANCA)}")


# Entrada de dados
print("Digite o valor de 3 vendas:")

venda1 = float(input("Venda 1: R$ "))
venda2 = float(input("Venda 2: R$ "))
venda3 = float(input("Venda 3: R$ "))

# Chamada da função
analisar_vendas(venda1, venda2, venda3)

"""# Parte 3

## 1.

R: A média bateu o esperado no valor de 1766.66, o código tomou a desição que eu esperava.



## 2.

R: Risco de manipulação não autorizada podendo gerar fraude.



## 3.

R: Depois de ter criado a classe "LIMITE_SEGURANCA" eu troquei o "C" por "Ç" em todos as partes que chamavam essa variável, e o sistema estava lendo uma variaveel que não existia.
"""